FROM amazoncorretto:21-alpine-full

WORKDIR /app

COPY target/BSConfigServer-0.0.1-SNAPSHOT.jar /app/BSConfigServer-0.0.1-SNAPSHOT.jar

EXPOSE ${SERVER_PORT}

ENV ACTIVE_PROFILE=${ACTIVE_PROFILE}
ENV CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PASSWORD}
ENV CONFIG_SERVER_USERNAME=${CONFIG_SERVER_USERNAME}
ENV GIT_PASSWORD=${GIT_PASSWORD}
ENV GIT_URI=${GIT_URI}
ENV GIT_USERNAME=${GIT_USERNAME}
ENV EUREKA_URL=${EUREKA_URL}
ENV EXTERNAL_IP=${EXTERNAL_IP}

ENTRYPOINT ["java", "-jar", "/app/BSConfigServer-0.0.1-SNAPSHOT.jar"]