FROM amazoncorretto:21-alpine-full

WORKDIR /app

COPY target/BSConfigServer-0.0.1-SNAPSHOT.jar /app/BSConfigServer-0.0.1-SNAPSHOT.jar

EXPOSE ${SERVER_PORT}

ENV ACTIVE_PROFILE=${ACTIVE_PROFILE}
ENV DISCOVERY_PASSWORD=${DISCOVERY_PASSWORD}
ENV DISCOVERY_USERNAME=${DISCOVERY_USERNAME}
ENV GIT_PASSWORD=${GIT_PASSWORD}
ENV GIT_URI=${GIT_URI}
ENV GIT_USERNAME=${GIT_USERNAME}
ENV EUREKA_URL=${EUREKA_URL}

ENTRYPOINT ["java", "-jar", "/app/BSConfigServer-0.0.1-SNAPSHOT.jar"]