spring:
  datasource:
    url: ${DB_RELATED_URL}
    username: ${DB_RELATED_USERNAME}
    password: ${DB_RELATED_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

encoder:
  keysize: 128
  algorithm: AES

jwt:
  terminal:
    expiration_time:
      access: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics