transactionservice:
  deafultbankserviceaccountnumber: 4145000000000001

conversion:
  updatetime: 1000000

conversionservice:
  exchangeRateURL: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json