server:
  port: ${SERVER_PORT:8070}
spring:
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
  application:
    name: configserver
  profiles:
    active: ${ACTIVE_PROFILE}
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
        native:
          search-locations: file:./src/main/resources/config
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://${CONFIG_SERVER_USERNAME}:${CONFIG_SERVER_PASSWORD}@localhost:8008/eureka/}
  instance:
    prefer-ip-address: true
    ip-address: ${EXTERNAL_IP}
logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.config: DEBUG
